services:
  php:
    image: php:8.3-fpm
    container_name: php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y git unzip curl libpq-dev &&
        docker-php-ext-install pdo pdo_pgsql &&
        php artisan key:generate --ansi &&
        php artisan migrate &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      bash -c "
      composer install && 
      composer run post-root-package-install
      "

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: